version: "3.9"
services:
  service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mysqldb: 
        condition: healthcheck
    
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bolao
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root