version: "3.8"
services:
  service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mysqldb: 
        condition: service_healthy
    
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bolao
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
        test: "exit 0"